
@startuml ABasicUseCase

'UML Design Logistics
skinparam dpi 200
skinparam DefaultFontName Inconsolata

'Actors
actor Operator

'Usecases
usecase "Retrieve Information" as retrieveInformation
usecase "Assign Task" as assignTask

'Databases
database "robot database" as robot_database 

'Relationships
Operator -- retrieveInformation : "asks for information \n about particular robot"
Operator -- assignTask : "assign a room to a particular robot"
retrieveInformation -- robot_database : "requests infromation of \n robot with an id"
assignTask -- robot_database : "update robot information \n with new added task"

'Legend 
'Syntax from: https://stackoverflow.com/questions/30999290/how-to-generate-a-legend-with-colors-in-plantuml
' legend right
'     |Color| Type |
'     |<#red>| Assign Task to Robot|
'     |<#0099CC>| Retrieve Information about Robot|
' endlegend

@enduml


