@startuml

start
fork 
    :User presses Add Robot Button;
    :Get Size and Type from GUI;
    :Create Robot (size, type);
    :Add Robot to System;
    :Show Robot Added Confirmation to User;
fork again 
    :User presses Fix Button;
    :Get Robot ID from GUI;
    if ("Is Robot ID invalid?") then (yes)
        :show meesage: \n Robot ID is invalid;
    else if ("Is Robot ID faulty?") then (yes)
        :show meesage: \n Robot ID is not faulty;
    else
        :show meesage: \n Robot ID is fixed;
    endif

fork again 

    :User presses Show All Robots Button;
    :Show All Robot IDs;


fork again 
  :User presses Show Robot Status Button;
  :Get Robot ID from GUI;
  if ("Is Robot ID valid?") then (yes)
    :Robot Status: Operational/Not Operational;
  else
    :Robot ID is Invalid;
  endif

fork again 

  :User presses Quit Button;
  :End Simulation Thread;
  :Close GUI;

fork end

stop
@enduml
