@startuml ABasicSeqDiagram

actor User
participant UI
participant inputHandler 
participant backend

activate User 
User -> UI: Log in to the system 
ref over UI, inputHandler, backend : User_UI_login, returns typed UI to user
' UI --> User: display typed UI
User -> UI: Clicks on "Logs" Button/area
deactivate User

activate UI
UI -> inputHandler: Send request for data logs.
deactivate UI

activate inputHandler
inputHandler -> backend: Process the request in database calls.
deactivate inputHandler

' waits for the backend to return. Ensures error handling is done gracefully.
activate backend
return information
backend --> UI: Returns information.
deactivate backend

activate UI
UI --> User: Display screen with an area to select from dated raw data logs.
deactivate UI

'User is now displayed a file screen with an area that displays all relevant logs. 

activate User
User -> UI: Clicks on a specific log. 
deactivate User

activate UI
UI -> inputHandler: Passes the name of the log.
deactivate UI

activate inputHandler
inputHandler -> backend: Process the log request in a database call.
deactivate inputHandler

' waits for the backend to return. Ensures error handling is done gracefully.
activate backend
return information
backend --> UI: Returns information.
deactivate backend

activate UI
UI --> User: Display a screen that has all text from the specified data log.
deactivate UI