@startuml ABasicSeqDiagram


actor User
participant UI
participant inputHandler 
participant backend

activate User 
User -> UI: Log in to the system 
ref over UI, inputHandler, backend : User_UI_login, returns typed UI to user
' UI --> User: display typed UI
User -> UI: Clicks on "Assign Tasks" Button/area
deactivate User

activate UI
UI -> inputHandler: Send request for task pannel.
deactivate UI

activate inputHandler
inputHandler -> backend: Ask for relevant information regarding tasks and robot status.
deactivate inputHandler

' waits for the backend to return. Ensures error handling is done gracefully.
activate backend
return information
backend --> UI: Return information.
deactivate backend

activate UI
UI --> User: Display tasks with relevant information.
deactivate UI

'User is now displayed a task screen with an area to input tasks, along with current statuses of robot and overview of the simulation.

activate User
User -> UI: Inputs task and selects relevant robots. Hits "confirm/submit"
deactivate User

activate UI
UI -> inputHandler: Passes data.
deactivate UI

activate inputHandler
inputHandler -> backend: Processes input data. Calls for the relevant robots and task protocol.
deactivate inputHandler

' waits for the backend to return. Ensures error handling is done gracefully.
activate backend
return conf_or_error
backend --> UI: Returns confirmation message or error if problem.
deactivate backend

'User is now logged in with a simple UI availible to them
activate UI
UI --> User: Display task summary or error.
deactivate UI




@enduml

